### ISSUE TITLE
Neue Wachen werden nicht erkannt

### ISSUE THREAD

**Issue by MCFrankja** [ChaosKai/fahrzeugtableau#2]
Wenn ich neue Wachen baue, werden diese vom Tableau nicht erkannt. Woran kann das liegen?

**Comment by ChaosKai** [comment]
Auch dein Issue habe ich leider nicht gesehen. In der neuen Version findet der export nun Manuell statt. Sollte der Fehler trotzdem weiterhin auftreten, bitte melden.
